# Generated by Django 5.2.11 on 2026-02-25 07:02

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "mobile",
                    models.CharField(
                        db_index=True,
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Mobile must be 10-15 digits.",
                                regex="^\\d{10,15}$",
                            )
                        ],
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_staff", models.BooleanField(db_index=True, default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_mobile",
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BranchJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("STUDENT", "Student"), ("PARENT", "Parent")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("mobile", models.CharField(db_index=True, max_length=15)),
                ("full_name", models.CharField(blank=True, max_length=120)),
                (
                    "admission_no",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("roll_no", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=200)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="orgs.branch",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="join_requests_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="orgs.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "acct_branch_join_request",
            },
        ),
        migrations.CreateModel(
            name="OrgMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ORG_OWNER", "Org Owner"),
                            ("ORG_ADMIN", "Org Admin"),
                            ("BRANCH_ADMIN", "Branch Admin"),
                            ("TEACHER", "Teacher"),
                            ("STAFF", "Staff"),
                            ("STUDENT", "Student"),
                            ("PARENT", "Parent"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending"),
                            ("SUSPENDED", "Suspended"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships",
                        to="orgs.branch",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="orgs.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "org_membership",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["mobile"], name="auth_user_m_mobile_90b1f9_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_staff"], name="auth_user_m_is_acti_2ec673_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branchjoinrequest",
            index=models.Index(
                fields=["branch", "role", "status", "created_at"],
                name="acct_branch_branch__fb2a21_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="branchjoinrequest",
            index=models.Index(
                fields=["organisation", "status"], name="acct_branch_organis_115255_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branchjoinrequest",
            index=models.Index(
                fields=["mobile", "status"], name="acct_branch_mobile_30efcd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="branchjoinrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("branch", "role", "mobile"),
                name="uq_branch_role_mobile_pending",
            ),
        ),
        migrations.AddIndex(
            model_name="orgmembership",
            index=models.Index(
                fields=["organisation", "role", "status"],
                name="org_members_organis_301ef2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orgmembership",
            index=models.Index(
                fields=["branch", "role", "status"],
                name="org_members_branch__6c81cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orgmembership",
            index=models.Index(
                fields=["user", "status"], name="org_members_user_id_ffd327_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="orgmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "organisation", "role", "branch"),
                name="uq_user_org_role_branch",
            ),
        ),
    ]
