# Generated by Django 5.2.11 on 2026-02-25 07:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("STARTER", "Starter"),
                            ("GROWTH", "Growth"),
                            ("PRO", "Pro"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "price_monthly_inr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("student_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("branch_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("teacher_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("feature_whatsapp_marketing", models.BooleanField(default=False)),
                ("feature_id_cards", models.BooleanField(default=True)),
                ("feature_reviews", models.BooleanField(default=True)),
                ("feature_tests", models.BooleanField(default=True)),
                ("feature_geo_attendance", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "bill_subscription_plan",
            },
        ),
        migrations.CreateModel(
            name="FeeInvoice",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=24, unique=True
                    ),
                ),
                ("period_year", models.PositiveSmallIntegerField(db_index=True)),
                ("period_month", models.PositiveSmallIntegerField(db_index=True)),
                ("due_date", models.DateField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DUE", "Due"),
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partial"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DUE",
                        max_length=10,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="academics.batch",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="orgs.branch",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="orgs.organisation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="academics.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "bill_fee_invoice",
            },
        ),
        migrations.CreateModel(
            name="FeePlan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("ONE_TIME", "One Time")],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_plans",
                        to="academics.batch",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_plans",
                        to="orgs.branch",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_plans",
                        to="orgs.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "bill_fee_plan",
            },
        ),
        migrations.CreateModel(
            name="PaymentSettings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("account_holder_name", models.CharField(blank=True, max_length=120)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("account_number", models.CharField(blank=True, max_length=40)),
                ("ifsc_code", models.CharField(blank=True, max_length=20)),
                ("upi_id", models.CharField(blank=True, max_length=80)),
                (
                    "upi_qr_image",
                    models.ImageField(blank=True, null=True, upload_to="payments/qr/"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_settings",
                        to="orgs.branch",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_settings",
                        to="orgs.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "bill_payment_settings",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=26, unique=True
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK", "Bank Transfer"),
                            ("UPI", "UPI"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "proof_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="payments/proof/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=200)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="orgs.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="billing.feeinvoice",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="orgs.organisation",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="academics.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "bill_payment_transaction",
            },
        ),
        migrations.CreateModel(
            name="OrganisationSubscription",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELLED", "Cancelled"),
                            ("TRIAL", "Trial"),
                        ],
                        db_index=True,
                        default="TRIAL",
                        max_length=12,
                    ),
                ),
                (
                    "started_on",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("expires_on", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "trial_ends_on",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="orgs.organisation",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="org_subscriptions",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "bill_org_subscription",
            },
        ),
        migrations.AddIndex(
            model_name="feeinvoice",
            index=models.Index(
                fields=["branch", "status", "due_date"],
                name="bill_fee_in_branch__a151c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feeinvoice",
            index=models.Index(
                fields=["organisation", "status"], name="bill_fee_in_organis_ea55c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feeinvoice",
            index=models.Index(
                fields=["student", "status"], name="bill_fee_in_student_975592_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feeinvoice",
            constraint=models.UniqueConstraint(
                fields=("student", "period_year", "period_month"),
                name="uq_student_invoice_period",
            ),
        ),
        migrations.AddIndex(
            model_name="feeplan",
            index=models.Index(
                fields=["branch", "batch"], name="bill_fee_pl_branch__d4ca71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feeplan",
            index=models.Index(
                fields=["organisation", "branch"], name="bill_fee_pl_organis_4ee574_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentsettings",
            index=models.Index(
                fields=["organisation", "is_active"],
                name="bill_paymen_organis_dbb60d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["branch", "status", "paid_at"],
                name="bill_paymen_branch__8b8a77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["organisation", "status", "paid_at"],
                name="bill_paymen_organis_6a6b48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["student", "paid_at"], name="bill_paymen_student_a89cf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["mode", "status"], name="bill_paymen_mode_bc6bcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organisationsubscription",
            index=models.Index(
                fields=["status", "expires_on"], name="bill_org_su_status_1c9866_idx"
            ),
        ),
    ]
