# Generated by Django 5.2.11 on 2026-02-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_batch_days_of_week_batchscheduleday'),
        ('billing', '0001_initial'),
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feeinvoice',
            name='uq_student_invoice_period',
        ),
        migrations.AddConstraint(
            model_name='feeinvoice',
            constraint=models.UniqueConstraint(fields=('student', 'batch', 'period_year', 'period_month'), name='uq_student_batch_invoice_period'),
        ),
    ]
