# Generated by Django 5.2.11 on 2026-02-25 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentParentLink",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("relation", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "db_table": "acad_student_parent_link",
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=22, unique=True
                    ),
                ),
                ("admission_no", models.CharField(db_index=True, max_length=32)),
                ("roll_no", models.CharField(blank=True, db_index=True, max_length=20)),
                (
                    "is_active_for_login",
                    models.BooleanField(db_index=True, default=False),
                ),
            ],
            options={
                "db_table": "acad_student_profile",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=80)),
            ],
            options={
                "db_table": "acad_subject",
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=22, unique=True
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("designation", models.CharField(blank=True, max_length=60)),
                (
                    "is_active_for_login",
                    models.BooleanField(db_index=True, default=True),
                ),
            ],
            options={
                "db_table": "acad_teacher_profile",
            },
        ),
        migrations.CreateModel(
            name="TimeTableSlot",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Mon"),
                            (2, "Tue"),
                            (3, "Wed"),
                            (4, "Thu"),
                            (5, "Fri"),
                            (6, "Sat"),
                            (7, "Sun"),
                        ],
                        db_index=True,
                    ),
                ),
                ("start_time", models.TimeField(db_index=True)),
                ("end_time", models.TimeField(db_index=True)),
                ("room", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "db_table": "acad_timetable_slot",
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=120)),
                ("code", models.CharField(db_index=True, max_length=24)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("days_of_week", models.CharField(blank=True, max_length=20)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="orgs.branch",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="orgs.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "acad_batch",
            },
        ),
        migrations.CreateModel(
            name="BatchEnrollment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("LEFT", "Left"),
                            ("PAUSED", "Paused"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "joined_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("left_on", models.DateField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="academics.batch",
                    ),
                ),
            ],
            options={
                "db_table": "acad_batch_enrollment",
            },
        ),
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "is_active_for_login",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="orgs.branch",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="orgs.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "acad_parent_profile",
            },
        ),
    ]
