# Generated by Django 5.2.11 on 2026-02-25 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="parentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentparentlink",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_links",
                to="academics.parentprofile",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="orgs.branch",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="orgs.organisation",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentparentlink",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_links",
                to="academics.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="batchenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="orgs.branch",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="orgs.organisation",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="orgs.branch",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="orgs.organisation",
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_slots",
                to="academics.batch",
            ),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_slots",
                to="orgs.branch",
            ),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_slots",
                to="orgs.organisation",
            ),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timetable_slots",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="timetableslot",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetable_slots",
                to="academics.teacherprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["organisation", "branch", "status"],
                name="acad_batch_organis_1b749b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["branch", "status"], name="acad_batch_branch__e4f834_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(
                fields=("branch", "code"), name="uq_batch_branch_code"
            ),
        ),
        migrations.AddIndex(
            model_name="parentprofile",
            index=models.Index(
                fields=["branch", "is_active_for_login"],
                name="acad_parent_branch__063863_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["branch", "is_active_for_login"],
                name="acad_studen_branch__618869_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["organisation", "branch"], name="acad_studen_organis_c48822_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.UniqueConstraint(
                fields=("organisation", "admission_no"), name="uq_student_org_admno"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentparentlink",
            constraint=models.UniqueConstraint(
                fields=("student", "parent"), name="uq_student_parent"
            ),
        ),
        migrations.AddIndex(
            model_name="batchenrollment",
            index=models.Index(
                fields=["batch", "status"], name="acad_batch__batch_i_24588e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batchenrollment",
            index=models.Index(
                fields=["student", "status"], name="acad_batch__student_1ac11c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="batchenrollment",
            constraint=models.UniqueConstraint(
                fields=("batch", "student"), name="uq_batch_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("branch", "name"), name="uq_subject_branch_name"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["branch", "is_active_for_login"],
                name="acad_teache_branch__6b0ffd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["organisation", "branch"], name="acad_teache_organis_bffef3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timetableslot",
            index=models.Index(
                fields=["batch", "weekday", "start_time"],
                name="acad_timeta_batch_i_e9827c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetableslot",
            index=models.Index(
                fields=["branch", "weekday", "start_time"],
                name="acad_timeta_branch__7b5f99_idx",
            ),
        ),
    ]
