# Generated by Django 5.2.11 on 2026-02-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='days_of_week',
        ),
        migrations.CreateModel(
            name='BatchScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri'), (6, 'Sat'), (7, 'Sun')], db_index=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_days', to='academics.batch')),
            ],
            options={
                'db_table': 'acad_batch_schedule_day',
                'indexes': [models.Index(fields=['batch', 'weekday'], name='acad_batch__batch_i_f904f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'weekday'), name='uq_batch_schedule_day')],
            },
        ),
    ]
