# Generated by Django 5.2.11 on 2026-02-25 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=24, unique=True
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=140)),
                ("message", models.TextField()),
                (
                    "audience_type",
                    models.CharField(
                        choices=[
                            ("ALL_STUDENTS", "All Students"),
                            ("ALL_PARENTS", "All Parents"),
                            ("ALL_TEACHERS", "All Teachers"),
                            ("BATCHES", "Selected Batches"),
                            ("BRANCH", "Branch Wide"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_pinned", models.BooleanField(db_index=True, default=False)),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="orgs.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="orgs.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "com_announcement",
            },
        ),
        migrations.CreateModel(
            name="AnnouncementBatchTarget",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_targets",
                        to="comms.announcement",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_targets",
                        to="academics.batch",
                    ),
                ),
            ],
            options={
                "db_table": "com_announcement_batch_target",
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "ntype",
                    models.CharField(
                        choices=[
                            ("ANNOUNCEMENT", "Announcement"),
                            ("FEE", "Fee"),
                            ("ATTENDANCE", "Attendance"),
                            ("TEST", "Test"),
                            ("GENERAL", "General"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("body", models.TextField(blank=True)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "com_user_notification",
            },
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["branch", "published_at"], name="com_announc_branch__afbe2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["organisation", "published_at"],
                name="com_announc_organis_d98181_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["branch", "is_pinned", "published_at"],
                name="com_announc_branch__38b23b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="announcementbatchtarget",
            constraint=models.UniqueConstraint(
                fields=("announcement", "batch"), name="uq_announcement_batch"
            ),
        ),
        migrations.AddIndex(
            model_name="usernotification",
            index=models.Index(
                fields=["user", "is_read", "created_at"],
                name="com_user_no_user_id_4baad1_idx",
            ),
        ),
    ]
