# Generated by Django 5.2.11 on 2026-02-25 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(db_index=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="PUBLISHED",
                        max_length=10,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="homework/"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="academics.batch",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="orgs.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homeworks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="orgs.organisation",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homeworks",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "assess_homework",
            },
        ),
        migrations.CreateModel(
            name="HomeworkSubmission",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text_answer", models.TextField(blank=True)),
                (
                    "file_answer",
                    models.FileField(
                        blank=True, null=True, upload_to="homework/submissions/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("LATE", "Late"),
                            ("CHECKED", "Checked"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=10,
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("feedback", models.CharField(blank=True, max_length=300)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homework_checked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assessments.homework",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_submissions",
                        to="academics.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "assess_homework_submission",
            },
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(db_index=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="materials/"),
                ),
                ("link_url", models.URLField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="academics.batch",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="orgs.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="orgs.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "assess_material",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=160)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("UNIT", "Unit Test"),
                            ("MOCK", "Mock"),
                            ("FINAL", "Final"),
                            ("CUSTOM", "Custom"),
                        ],
                        db_index=True,
                        default="CUSTOM",
                        max_length=10,
                    ),
                ),
                (
                    "scheduled_on",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("duration_min", models.PositiveIntegerField(default=60)),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "passing_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="PUBLISHED",
                        max_length=12,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="academics.batch",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="orgs.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="orgs.organisation",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tests",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "assess_test",
            },
        ),
        migrations.CreateModel(
            name="StudentTestResult",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "marks_obtained",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("grade", models.CharField(blank=True, max_length=10)),
                ("remarks", models.CharField(blank=True, max_length=200)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results_entered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="academics.studentprofile",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="assessments.test",
                    ),
                ),
            ],
            options={
                "db_table": "assess_student_test_result",
            },
        ),
        migrations.AddIndex(
            model_name="homework",
            index=models.Index(
                fields=["batch", "status", "due_date"],
                name="assess_home_batch_i_0cd59f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="homework",
            index=models.Index(
                fields=["branch", "status", "created_at"],
                name="assess_home_branch__fe7dff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="homeworksubmission",
            index=models.Index(
                fields=["student", "created_at"], name="assess_home_student_4571c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homeworksubmission",
            index=models.Index(
                fields=["homework", "status"], name="assess_home_homewor_2d54a3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="homeworksubmission",
            constraint=models.UniqueConstraint(
                fields=("homework", "student"), name="uq_homework_student"
            ),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(
                fields=["batch", "created_at"], name="assess_mate_batch_i_4077a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(
                fields=["branch", "created_at"], name="assess_mate_branch__c979e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["batch", "status", "scheduled_on"],
                name="assess_test_batch_i_ffd8fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["branch", "status", "scheduled_on"],
                name="assess_test_branch__b06e7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studenttestresult",
            index=models.Index(
                fields=["student", "created_at"], name="assess_stud_student_70cd56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studenttestresult",
            index=models.Index(
                fields=["test", "marks_obtained"], name="assess_stud_test_id_dee64b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studenttestresult",
            constraint=models.UniqueConstraint(
                fields=("test", "student"), name="uq_test_student"
            ),
        ),
    ]
