# Generated by Django 5.2.11 on 2026-02-25 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppCampaign",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=24, unique=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=160)),
                ("message", models.TextField()),
                (
                    "target_group",
                    models.CharField(
                        choices=[
                            ("ALL_STUDENTS", "All Students"),
                            ("ALL_PARENTS", "All Parents"),
                            ("ALL_TEACHERS", "All Teachers"),
                            ("BATCHES", "Selected Batches"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("SENDING", "Sending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wa_campaigns",
                        to="orgs.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wa_campaigns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wa_campaigns",
                        to="orgs.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "mkt_wa_campaign",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppCampaignBatchTarget",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wa_campaign_targets",
                        to="academics.batch",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_targets",
                        to="marketing.whatsappcampaign",
                    ),
                ),
            ],
            options={
                "db_table": "mkt_wa_campaign_batch_target",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessageLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("to_mobile", models.CharField(db_index=True, max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=12,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("error", models.CharField(blank=True, max_length=200)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wa_message_logs",
                        to="orgs.branch",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_logs",
                        to="marketing.whatsappcampaign",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wa_message_logs",
                        to="orgs.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wa_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mkt_wa_message_log",
            },
        ),
        migrations.AddIndex(
            model_name="whatsappcampaign",
            index=models.Index(
                fields=["branch", "status", "scheduled_at"],
                name="mkt_wa_camp_branch__d6397c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappcampaign",
            index=models.Index(
                fields=["organisation", "status", "scheduled_at"],
                name="mkt_wa_camp_organis_25d1e4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappcampaignbatchtarget",
            constraint=models.UniqueConstraint(
                fields=("campaign", "batch"), name="uq_campaign_batch"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessagelog",
            index=models.Index(
                fields=["campaign", "status", "created_at"],
                name="mkt_wa_mess_campaig_5213d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessagelog",
            index=models.Index(
                fields=["branch", "status", "created_at"],
                name="mkt_wa_mess_branch__ab551a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessagelog",
            index=models.Index(
                fields=["to_mobile", "created_at"],
                name="mkt_wa_mess_to_mobi_00299c_idx",
            ),
        ),
    ]
