# Generated by Django 5.2.11 on 2026-02-25 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("session_date", models.DateField(db_index=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("allow_student_self_mark", models.BooleanField(default=True)),
                ("max_self_mark_distance_m", models.PositiveIntegerField(default=50)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="academics.batch",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="orgs.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="orgs.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "att_class_session",
            },
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("LEAVE", "Leave"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "marked_by_type",
                    models.CharField(
                        choices=[
                            ("TEACHER", "Teacher"),
                            ("STUDENT_GEO", "Student Geo"),
                            ("ADMIN", "Admin"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "marked_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "marked_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "marked_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "distance_from_branch_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academics.batch",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="orgs.branch",
                    ),
                ),
                (
                    "marked_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_marked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="orgs.organisation",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="attendance.classsession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academics.studentprofile",
                    ),
                ),
            ],
            options={
                "db_table": "att_student_attendance",
            },
        ),
        migrations.AddIndex(
            model_name="classsession",
            index=models.Index(
                fields=["branch", "session_date"], name="att_class_s_branch__07f879_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsession",
            index=models.Index(
                fields=["batch", "session_date"], name="att_class_s_batch_i_fafc2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsession",
            index=models.Index(
                fields=["organisation", "session_date"],
                name="att_class_s_organis_a5f52a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classsession",
            index=models.Index(
                fields=["status", "session_date"], name="att_class_s_status_de2b68_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="classsession",
            constraint=models.UniqueConstraint(
                fields=("batch", "session_date", "start_time"),
                name="uq_session_batch_date_time",
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["session", "status"], name="att_student_session_590efc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["student", "marked_at"], name="att_student_student_5e8955_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["branch", "marked_at"], name="att_student_branch__389298_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentattendance",
            index=models.Index(
                fields=["batch", "marked_at"], name="att_student_batch_i_272d3e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentattendance",
            constraint=models.UniqueConstraint(
                fields=("session", "student"), name="uq_session_student_attendance"
            ),
        ),
    ]
