# Generated by Django 5.2.11 on 2026-02-25 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("author_name", models.CharField(blank=True, max_length=120)),
                (
                    "author_mobile",
                    models.CharField(blank=True, db_index=True, max_length=15),
                ),
                ("rating", models.PositiveSmallIntegerField(db_index=True)),
                ("title", models.CharField(blank=True, max_length=140)),
                ("comment", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("moderation_note", models.CharField(blank=True, max_length=200)),
                (
                    "author_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews_written",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="orgs.branch",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews_moderated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="orgs.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "rev_review",
                "indexes": [
                    models.Index(
                        fields=["organisation", "status", "created_at"],
                        name="rev_review_organis_97e4d7_idx",
                    ),
                    models.Index(
                        fields=["branch", "status", "created_at"],
                        name="rev_review_branch__c737e4_idx",
                    ),
                    models.Index(
                        fields=["organisation", "rating"],
                        name="rev_review_organis_a8dd58_idx",
                    ),
                ],
            },
        ),
    ]
