# Generated by Django 5.2.11 on 2026-02-25 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=180)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("owner_name", models.CharField(blank=True, max_length=120)),
                (
                    "owner_mobile",
                    models.CharField(blank=True, db_index=True, max_length=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "db_table": "org_organisation",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="org_organis_status_2cb462_idx",
                    ),
                    models.Index(fields=["name"], name="org_organis_name_7dc7ee_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=140)),
                (
                    "public_code",
                    models.CharField(db_index=True, max_length=12, unique=True),
                ),
                ("address_line1", models.CharField(max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(db_index=True, max_length=64)),
                ("state", models.CharField(blank=True, max_length=64)),
                ("pincode", models.CharField(blank=True, max_length=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "geo_center_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "geo_center_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("geo_radius_m", models.PositiveIntegerField(default=50)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="orgs.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "org_branch",
                "indexes": [
                    models.Index(
                        fields=["organisation", "status"],
                        name="org_branch_organis_62352f_idx",
                    ),
                    models.Index(
                        fields=["organisation", "city"],
                        name="org_branch_organis_077d9f_idx",
                    ),
                    models.Index(
                        fields=["public_code"], name="org_branch_public__5c89ce_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organisation", "name"), name="uq_branch_org_name"
                    )
                ],
            },
        ),
    ]
