# Generated by Django 5.2.11 on 2026-02-25 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdCardTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=120)),
                ("layout_json", models.JSONField(blank=True, default=dict)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idcard_templates",
                        to="orgs.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idcard_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idcard_templates",
                        to="orgs.organisation",
                    ),
                ),
            ],
            options={
                "db_table": "idc_template",
            },
        ),
        migrations.CreateModel(
            name="GeneratedIdCard",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="idcards/"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="id_cards",
                        to="academics.studentprofile",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="id_cards",
                        to="academics.teacherprofile",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_cards",
                        to="idcards.idcardtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "idc_generated",
            },
        ),
        migrations.AddIndex(
            model_name="idcardtemplate",
            index=models.Index(
                fields=["organisation", "created_at"],
                name="idc_templat_organis_793b19_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generatedidcard",
            index=models.Index(
                fields=["template", "created_at"], name="idc_generat_templat_8e2d20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedidcard",
            index=models.Index(
                fields=["student", "created_at"], name="idc_generat_student_bd1519_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedidcard",
            index=models.Index(
                fields=["teacher", "created_at"], name="idc_generat_teacher_dd05fa_idx"
            ),
        ),
    ]
